name: process manager deployment

on:
  workflow_dispatch:

env:
  TEAM: dummyteam
  ACR: dummy_acr
  SERVICE: demo

jobs:
  build:
    runs-on: runner
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build
        run: sh "./scripts/build.sh"

      - name: Compute image tag
        id: get_image_name
        run: |
          GIT_HEAD_SHA=$(git rev-parse --short HEAD)
          IMAGE_NAME="$ACR/$TEAM/$SERVICE:$GIT_HEAD_SHA"
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - uses: dummt_Acr
        with:
          acr: ${{ env.ACR }}

      - name: Build and push image
        run: |
          docker build . -t ${{ steps.get_image_name.outputs.image_name }}
          docker push ${{ steps.get_image_name.outputs.image_name }}

    outputs:
      image_name: ${{ steps.get_image_name.outputs.image_name }}